name: Weather Alert

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run-weather-alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python weather_alert.py